# Generated by Django 5.1 on 2024-08-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_timeline_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
