# Generated by Django 5.1 on 2024-08-16 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_profile_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topskilldetails',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='mysite.topskillcategory'),
        ),
    ]
