# Generated by Django 5.1 on 2024-08-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_skillinsightcategory_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
