# Generated by Django 5.1 on 2024-08-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactuser',
            old_name='full_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image_url',
            field=models.ImageField(upload_to='certificate/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_image',
            field=models.ImageField(upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hero_image',
            field=models.ImageField(upload_to='hero/'),
        ),
    ]
